image:
  repository: tccr.io/truecharts/homarr
  tag: v0.14.0@sha256:593575934e7b9db262b28263154bcf2e858fc3afcb430c8f8ded28a854d78361
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  config:
    enabled: true
    mountPath: "/app/data/configs"
  icons:
    enabled: true
    mountPath: "/app/public/icons"
  data:
    enabled: true
    mountPath: "/data"  
portal:
  open:
    enabled: true
